services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
  eureka-server:
      image: oussamazaoui872/eurekaserver:0.0.1-SNAPSHOT
      container_name: eureka-server
      ports:
        - "8761:8761"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      networks:
        - spring
      depends_on:
        - zipkin
  apigw:
      image: oussamazaoui872/apigateway:0.0.1-SNAPSHOT
      container_name: apigw
      ports:
        - "8091:8091"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      networks:
        - spring
      depends_on:
        - zipkin
        - eureka-server
  customer:
      image: oussamazaoui872/customer:1.0.0
      container_name: customer
      ports:
        - "8082:8082"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      networks:
        - spring
        - postgres
      depends_on:
        - zipkin
        - postgres
        - rabbitmq
  fraud:
      image: oussamazaoui872/fraud:0.0.1-SNAPSHOT
      container_name: fraud
      ports:
        - "8083:8083"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      networks:
        - spring
        - postgres
      depends_on:
        - zipkin
        - postgres
        - rabbitmq
  notification:
      image: oussamazaoui872/notification:0.0.1-SNAPSHOT
      container_name: notification
      ports:
        - "8089:8089"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      networks:
        - spring
        - postgres
      depends_on:
        - zipkin
        - postgres
        - rabbitmq
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

