server:
  port: 8082
spring:
  application:
    name: customer
  cloud:
    compatibility-verifier:
      enabled: false
  sleuth:
    sampler:
      probability: 1.0

  datasource:
    password: 1234567890
    url: jdbc:postgresql://postgres:5432/test
    username: oussama
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
